
```{r}
library(readr)
gd_decipher <- read_csv("data/decipher_related/glycanDatabase.csv", show_col_types = FALSE)

# pGlyco Human
gd_pglyco <- read.table("data/pGlyco3_related/pGlyco-N-Human.txt", header = FALSE, skip = 1)
gd_pglyco <- gd_pglyco$V1 %>% unique()

length(gd_decipher$StructureInformation); length(gd_pglyco)
```
# Compare gd_decipher with gd_pglyco3 under pGlyco3 format
# pGlyco3 format has to be reordered (for the same length branch)
```{r}
# Decipher to pGlyco3 format
wurcs <- gd_decipher$StructureInformation
wurcs <- wurcs[-1]
gd_decipher_in_pGlyco3_format <- lapply(wurcs, function(w) {
  w %>% wurcs_to_tree() %>% tree_to_pGlyco3()
}) %>% unlist
gd_decipher_in_pGlyco3_format <- unique(gd_decipher_in_pGlyco3_format)

# pGlyco3 format reorder
gd_pGlyco3_in_pGlyco3_format <- lapply(gd_pglyco, function(g) {
  g %>% pGlyco3_to_tree %>% tree_to_pGlyco3()
}) %>% unlist
gd_pGlyco3_in_pGlyco3_format <- unique(gd_pGlyco3_in_pGlyco3_format)

common <- intersect(gd_decipher_in_pGlyco3_format, 
                    gd_pGlyco3_in_pGlyco3_format)
length(gd_decipher_in_pGlyco3_format)
length(gd_pGlyco3_in_pGlyco3_format)
length(common)

diff <- setdiff(gd_pGlyco3_in_pGlyco3_format, 
                gd_decipher_in_pGlyco3_format)
diff[1] 

diff2 <- setdiff(gd_decipher_in_pGlyco3_format, 
                 gd_pGlyco3_in_pGlyco3_format)
diff2[100] 

```

# Compare gd_decipher with gd_pglyco3 under tree structure
```{r}
# Compare gd_decipher with gd_pglyco3 under igraph format
library(igraph)

# Decipher to tree format
wurcs <- gd_decipher$StructureInformation
wurcs <- wurcs[-1]
gd_decipher_in_tree_format <- lapply(wurcs, function(w) {
  w %>% wurcs_to_tree() %>% get_igraph_tree()
})

# pGlyco3 to tree format
gd_pGlyco3_in_tree_format <- lapply(gd_pglyco, function(g) {
  g %>% pGlyco3_to_tree() %>% get_igraph_tree()
})

is_same_tree <- function(g1, g2) {
  igraph:::isomorphic_vf2_impl(
    g1,
    g2,
    vertex.color1 = match(V(g1)$residue, LETTERS),
    vertex.color2 = match(V(g2)$residue, LETTERS)
  )$iso
}

match_idx <- integer(length(gd_pGlyco3_in_tree_format))

for (i in seq_along(gd_pGlyco3_in_tree_format)) {
  print(i)
  g1  <- gd_pGlyco3_in_tree_format[[i]]
  hit <- which(vapply(gd_decipher_in_tree_format,
                      is_same_tree, logical(1), g2 = g1))
  match_idx[i] <- if (length(hit)) paste(hit, collapse = "_") else 0
}

sum(match_idx != "0")
```

