#' Plot a glycan structure represented as an igraph tree
#'
#' @description
#' Visualize a glycan structure encoded as an igraph object produced by
#' \code{\link{build_glycan_igraph}}. This plot is mainly intended for inspecting
#' glycan topology (branching, residue types, connectivity).
#'
#' @param g
#' An igraph object representing a glycan tree from \code{\link{build_glycan_igraph}}.
#'
#'
#'
#' @return A glycan topology plot is drawn as a side effect.
#'
#' @import igraph
#' @export
plot_glycan_tree <- function(g) {
  plot(
    g,
    layout = igraph::layout_as_tree(g, root = "a"),
    vertex.label = igraph::V(g)$type,
    vertex.color = igraph::V(g)$color,
    vertex.size = 30,
    edge.arrow.size = 1,
    main = "Glycan Topology"
  )
}


#' Plot the distribution of a glycan trait across experimental groups
#'
#' @description
#' Generate two diagnostic plots—a histogram and a boxplot—for a selected
#' glycan trait at a specific site/protein feature.
#' This function extracts GPSM-level values from a trait matrix stored in a
#' `SummarizedExperiment`, subsets them by group, removes missing values,
#' and visualizes the resulting distribution.
#'
#' @param trait_se
#' A SummarizedExperiment object generated by \link{build_trait_se},
#' containing one assay matrix per glycan trait.
#'
#' @param group_col
#' Column name in `colData(trait_se)` that defines sample group membership.
#'
#' @param group_levels
#' Character vector specifying the group values to include in the plot.
#' Typically two values (e.g. `c("Control","Treatment")`).
#'
#' @param trait_name
#' Name of the glycan trait to plot. Must match an assay name in
#' `assays(trait_se)`.
#'
#' @param feature
#' Row identifier within the trait matrix (peptide, or protein).
#' Must match a row name in `assays(trait_se)[[trait_name]]`.
#'
#' @return
#' A named list of two `ggplot2` objects:
#' * `p_hist` — histogram of trait intensities
#' * `p_box`  — boxplot with jitter overlay
#'
#' @import ggplot2
#' @importFrom SummarizedExperiment assays colData rowData
#' @export
plot_trait_distribution <- function(trait_se,
                                    group_col,
                                    group_levels,
                                    trait_name,
                                    feature) {
  assays <- assays(trait_se)
  coldata <- colData(trait_se)
  rowdata <- rowData(trait_se)

  # extract abundance vector for the specified trait and feature row
  abund <- assays[[trait_name]][feature, ]
  label <- coldata[[group_col]]

  # subset: only PSMs belonging to selected group levels
  col_ind <- label %in% group_levels
  label_new <- label[col_ind]
  abund_new <- abund[col_ind]

  # keep non-NA values
  ind <- !is.na(abund_new)
  label_new <- label_new[ind]
  abund_new <- abund_new[ind]

  # build plotting data
  df_plot <- data.frame(
    Abundance = as.numeric(abund_new),
    Group     = factor(label_new, levels = group_levels)
  )

  ## freq hist
  p_freq <-
    ggplot(df_plot, aes(x = Abundance, fill = Group)) +
    geom_histogram(
      aes(y = after_stat(count)),
      position = "dodge",
      color = "black",
      binwidth = max(1, ceiling(max(df_plot$Abundance) / 20))
    ) +
    scale_fill_manual(values = setNames(c("#e31a1c", "#1f78b4"), group_levels)) +
    labs(x = paste(trait_name, "Count at", feature), y = "PSM count") +
    theme_classic(base_size = 14) +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      axis.text.x = element_text(size = 14),
      axis.text.y = element_text(size = 12),
      legend.position = "top",
      legend.title = element_blank(),
      legend.text = element_text(size = 14)
    )

  p_box <- ggplot(df_plot, aes(x = Group, y = Abundance, fill = Group)) +
    geom_boxplot(width = 0.5, show.legend = FALSE) +
    geom_jitter(size = 1, width = 0.1, show.legend = FALSE) +
    scale_fill_manual(values = setNames(c("#e31a1c", "#1f78b4"), group_levels)) +
    labs(x = NULL, y = paste(trait_name, "Count at", feature)) +
    theme_classic(base_size = 14) +
    theme(
      axis.text.x = element_text(size = 14),
      axis.text.y = element_text(size = 12),
      legend.position = "top",
      legend.title = element_blank(),
      legend.text = element_text(size = 14)
    )

  return(list(p_hist = p_freq, p_box = p_box))
}
