#' Compute glycan traits from a parsed glycan tree
#'
#' Combine residue-level composition traits (see \code{count_residues}),
#' structural traits (see \code{compute_structural_traits}), and
#' user-defined motifs (see \code{compute_userdefined_traits})
#' into a unified trait vector.
#'
#' @param tree A parsed glycan tree from \code{\link{pGlyco3_to_tree}} or \code{\link{wurcs_to_tree}}.
#'
#' @param motifs Optional named list of user-defined glycan motifs.
#'
#' @return A named list of numeric trait values.
#'
#' @examples
#' # Example: parse a pGlyco3-style glycan expression into a tree
#' pGlyco_expr <- "(N(N(H(H(H))(H(H)(H)(H(H))))))"
#'
#' # Convert to glycan tree structure
#' tree <- pGlyco3_to_tree(pGlyco_expr)
#'
#' # Explore parsed nodes and edges
#' tree$node
#' tree$edge
#'
#' # Build igraph representation
#' g <- build_glycan_igraph(tree)
#' plot_glycan_tree(g)
#'
#' # Define user motifs for trait computation
#' user_motifs <- list(
#'   LinearH3 = list(
#'     node = c("H", "H", "H"),
#'     edge = c("a-b", "b-c")
#'   ),
#'   FucBranch = list(
#'     node = c("H", "N", "F"),
#'     edge = c("a-b", "b-c")
#'   )
#' )
#'
#' # Compute glycan structural traits
#' compute_glycan_traits(tree, motifs = user_motifs)
#'
#' @export
compute_glycan_traits <- function(tree, motifs = NULL) {
  cnt_trait <- count_residues(tree)
  struct_trait <- compute_structural_traits(tree)
  ud_trait <- compute_userdefined_traits(tree, motifs)

  traits <- c(cnt_trait, struct_trait, ud_trait)
  as.list(traits)
}

#' Append computed glycan traits to a GPSM table
#'
#' Parse each unique glycan structure in a GPSM table, compute its
#' residue and structural traits, and expand the resulting trait
#' columns back to the full GPSM table.
#'
#' @param gpsm A GPSM table from either
#' \code{\link{read_pGlyco3_gpsm}} or \code{\link{read_decipher_gpsm}}.
#'
#' @param from One of `decipher` or `pGlyco3`.
#'
#' @param motifs Optional list of user-defined structural motifs.
#'
#' @return A modified GPSM table with appended trait columns.
#'
#' @keywords internal
#' @noRd
annotate_traits_to_gpsm <- function(gpsm, from, motifs) {
  # Split key GPSM columns and other metadata columns
  glycan <- unique(gpsm$GlycanStructure)

  # Select appropriate glycan-to-tree converter
  if (from == "decipher") {
    get_trait_vector <- function(glycan) {
      glycan_list <- wurcs_to_tree(glycan)
      res_list <- compute_glycan_traits(glycan_list, motifs)
      unlist(res_list)
    }
  } else if (from == "pGlyco3") {
    get_trait_vector <- function(glycan) {
      glycan_list <- pGlyco3_to_tree(glycan)
      res_list <- compute_glycan_traits(glycan_list, motifs)
      unlist(res_list)
    }
  } else {
    stop("`from` must be either 'decipher' or 'pGlyco3'. No traits were computed.")
  }

  # Compute traits for each glycan structure
  traits_list <- pbapply::pblapply(glycan, get_trait_vector)
  traits_columns <- do.call(rbind, traits_list)

  # add trait to psm matrix
  ind <- match(gpsm$GlycanStructure, glycan)
  traits_add <- traits_columns[ind, ]
  # combine the both
  gpsm <- cbind(gpsm, traits_add)

  gpsm$Peptide <- paste0(gpsm$Peptide, " (", gpsm$Protein, ")")
  gpsm
}

#' Compute site-level glycan trait means and heterogeneity scores
#'
#' Filter glycosylation sites by the number of observed glycoforms,
#' then calculate abundance-weighted glycan trait means and
#' heterogeneity scores (weighted variances) for each site within
#' each sample.
#'
#' For every `(File, Peptide)` combination, glycoforms are weighted
#' by their relative abundance. The weighted
#' mean of each glycan trait is reported as `*_mu`, and the weighted
#' variance is reported as `*_h`.
#'
#' @param gpsm_mat A GPSM table with glycan trait columns appended,
#' typically generated by
#' \code{\link{annotate_traits_to_gpsm}}.
#'
#' @param gf_thres Minimum number of distinct glycoforms required for
#' a site to be included. Sites with glycoform counts less than or
#' equal to this threshold are excluded. Default is 3.
#'
#' @return A data frame containing one row per `(File, Peptide)` site.
#' Columns ending in `_mu` are abundance-weighted mean glycan traits,
#' and columns ending in `_h` are abundance-weighted heterogeneity
#' scores.
#'
#' @keywords internal
#' @noRd
obtain_hscore_site <- function(gpsm_mat, gf_thres = 3) {
  # find glycoform
  n_glycoform <- ave(
    gpsm_mat$GlycanStructure,
    gpsm_mat$File,
    gpsm_mat$Peptide,
    FUN = function(x) length(unique(x))
  )
  # keep only those rows whose glycoform more than a give threshold
  gpsm_mat <- gpsm_mat[n_glycoform > gf_thres, ]
  site_total  <- stats::ave(gpsm_mat$Count, gpsm_mat$File, gpsm_mat$Peptide, FUN = sum)
  gpsm_mat$site_total  <- site_total
  gpsm_mat$site_ratio  <- gpsm_mat$Count / site_total
  glycan_cols <- setdiff(
    colnames(gpsm_mat),
    c("Protein", "Peptide", "GlycanStructure", "File", "Count",
      "site_total", "site_ratio", "protein_total", "protein_ratio"))

  mu_mat <- gpsm_mat[glycan_cols] * gpsm_mat$site_ratio
  mu_tab <- aggregate(
    mu_mat,
    by = list(File = gpsm_mat$File, Peptide = gpsm_mat$Peptide),
    FUN = sum
  )
  names(mu_tab)[-(1:2)] <- paste0(names(mu_tab)[-(1:2)], "_mu")

  tmp <- merge(gpsm_mat, mu_tab, by = c("File", "Peptide"))
  h_mat <- sapply(glycan_cols, function(m) {
    tmp$site_ratio * (tmp[[m]] - tmp[[paste0(m, "_mu")]])^2
  })
  h_tab <- aggregate(h_mat,
                     by = list(File = tmp$File, Peptide = tmp$Peptide),
                     FUN = sum)
  names(h_tab)[-(1:2)] <- paste0(names(h_tab)[-(1:2)], "_h")

  h_site <- merge(mu_tab, h_tab, by = c("File", "Peptide"))
  h_site
}


#' Compute protein-level glycan trait means and heterogeneity scores
#'
#' Filter proteins by the number of observed glycoforms, then calculate
#' abundance-weighted glycan trait means and heterogeneity scores
#' (weighted variances) for each protein within each sample.
#'
#' For every `(File, Protein)` combination, glycoforms are weighted by
#' their relative abundance (`Count / protein_total`). The weighted mean
#' of each glycan trait is reported as `*_mu`, and the weighted variance
#' is reported as `*_h`.
#'
#' @param gpsm_mat A GPSM table with glycan trait columns appended,
#' typically generated by
#' \code{\link{annotate_traits_to_gpsm}}.
#'
#' @param gf_thres Minimum number of distinct glycoforms required for a
#' protein to be included. Proteins with glycoform counts less than or
#' equal to this threshold are excluded. Default is 5.
#'
#' @return A data frame containing one row per `(File, Protein)`.
#' Columns ending in `_mu` are abundance-weighted mean glycan traits,
#' and columns ending in `_h` are abundance-weighted heterogeneity
#' scores.
#'
#' @keywords internal
#' @noRd
obtain_hscore_protein <- function(gpsm_mat, gf_thres = 5) {
  # find glycoform number per protein in each sample
  n_glycoform <- ave(
    gpsm_mat$GlycanStructure,
    gpsm_mat$File,
    gpsm_mat$Protein,
    FUN = function(x) length(unique(x))
  )

  # keep only proteins with more glycoforms than threshold
  gpsm_mat <- gpsm_mat[n_glycoform > gf_thres, ]

  protein_total <- stats::ave(
    gpsm_mat$Count,
    gpsm_mat$File,
    gpsm_mat$Protein,
    FUN = sum
  )

  gpsm_mat$protein_total <- protein_total
  gpsm_mat$protein_ratio <- gpsm_mat$Count / protein_total

  glycan_cols <- setdiff(
    colnames(gpsm_mat),
    c("Protein", "Peptide", "GlycanStructure", "File", "Count",
      "site_total", "site_ratio", "protein_total", "protein_ratio")
  )

  mu_mat <- gpsm_mat[glycan_cols] * gpsm_mat$protein_ratio

  mu_tab <- aggregate(
    mu_mat,
    by = list(File = gpsm_mat$File, Protein = gpsm_mat$Protein),
    FUN = sum
  )

  names(mu_tab)[-(1:2)] <- paste0(names(mu_tab)[-(1:2)], "_mu")

  tmp <- merge(gpsm_mat, mu_tab, by = c("File", "Protein"))

  h_mat <- sapply(glycan_cols, function(m) {
    tmp$protein_ratio * (tmp[[m]] - tmp[[paste0(m, "_mu")]])^2
  })

  h_tab <- aggregate(
    h_mat,
    by = list(File = tmp$File, Protein = tmp$Protein),
    FUN = sum
  )

  names(h_tab)[-(1:2)] <- paste0(names(h_tab)[-(1:2)], "_h")
  h_protein <- merge(mu_tab, h_tab, by = c("File", "Protein"))
  h_protein
}

#' Compute site- and protein-level glycan heterogeneity scores
#'
#' Annotate a GPSM table with glycan trait columns, then compute
#' abundance-weighted glycan trait means and heterogeneity scores at both
#' glycosylation-site and protein levels.
#'
#' For each site or protein within each sample, glycoforms are weighted by
#' their relative abundance. The weighted mean of each glycan trait is reported
#' as `*_mu`, and the weighted variance is reported as `*_h`.
#'
#' @param gpsm A GPSM table containing at least `Protein`, `Peptide`,
#'   `GlycanStructure`, `File`, and `Count`.
#' @param from Character; glycan format used in the GPSM input.
#'   One of `"decipher"` or `"pGlyco3"`.
#' @param motifs Optional named list of user-defined motif structures
#'   passed to \code{\link{compute_glycan_traits}}.
#'
#' @return A list with two data frames:
#' \describe{
#'   \item{h_site}{Site-level results with one row per `(File, Peptide)`.}
#'   \item{h_protein}{Protein-level results with one row per `(File, Protein)`.}
#' }
#' In both tables, columns ending in `_mu` are abundance-weighted mean glycan
#' traits, and columns ending in `_h` are abundance-weighted heterogeneity
#' scores.
#'
#' @examples
#' path <- system.file("extdata", "pGlyco3_gpsm_toyexample.txt",
#'   package = "glycoTraitR"
#' )
#' gpsm_toyexample <- read_pGlyco3_gpsm(path)
#'
#' hscore <- compute_hscore(
#'   gpsm = gpsm_toyexample,
#'   from = "pGlyco3",
#'   motifs = NULL
#' )
#'
#' head(hscore$h_site)
#' head(hscore$h_protein)
#'
#' @export
compute_hscore <- function(gpsm, from, motifs = NULL) {
  gpsm_mat <- annotate_traits_to_gpsm(gpsm, from, motifs)

  h_site <- obtain_hscore_site(gpsm_mat)
  h_protein <- obtain_hscore_protein(gpsm_mat)
  list(h_site = h_site, h_protein = h_protein)
}
